In [1]:
import numpy as np

In [2]:
hanning = np.hanning(25)
window = np.outer(hanning,hanning)

In [25]:
hanning

array([ 0.        ,  0.01703709,  0.0669873 ,  0.14644661,  0.25      ,
        0.37059048,  0.5       ,  0.62940952,  0.75      ,  0.85355339,
        0.9330127 ,  0.98296291,  1.        ,  0.98296291,  0.9330127 ,
        0.85355339,  0.75      ,  0.62940952,  0.5       ,  0.37059048,
        0.25      ,  0.14644661,  0.0669873 ,  0.01703709,  0.        ])

In [14]:
xx, yy = np.meshgrid([-16+ 8 * dx for dx in range(5)], [-16+ 8 * dx for dx in range(5)])

In [15]:
xx

array([[-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16]])

In [32]:
yy

array([[-16, -16, -16, -16, -16],
       [ -8,  -8,  -8,  -8,  -8],
       [  0,   0,   0,   0,   0],
       [  8,   8,   8,   8,   8],
       [ 16,  16,  16,  16,  16]])

In [19]:
np.tile( xx , 2 * 2).reshape((-1,5))

array([[-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16],
       [-16,  -8,   0,   8,  16]])